### ISSUE TITLE
Améliorer le système de récompenses

### ISSUE THREAD

**Issue by jillro** [iuliust/jlmPBback#8]
- [ ] cacher le moyen d'obtenir une récompense jusqu'à l'avoir obtenue
- [ ] remplacer les récompenses des numéros 50 à 5000 par des récompenses humoristiques. Éviter les titres qui font référence à une situation réelle  : être membre ou créateur.rice de grouep d'appui n'est pas une distinction honorifique, pas plus qu'être élu.e. Cela pourrait être mal perçu dans le mouvement.

**Comment by darckoune** [comment]
Pas d'accord avec le premier point, le meilleur moyen de motiver des gens à jouer c'est de leur donner des objectifs. C'est pas pour rien que la plupart des jeux ne cachent pas comment obtenir leurs achievements ! :)
Le second point ok pour les élus, mais pas pour les groupes d'appuis. Les trophées ne sont pas des "récompenses" mais reflètent ton investissement. Alors comparer quelqu'un qui fait plein d'appels à un membre/créateur de groupe d'appui (qui donc s'investit dans la campagne) me semble plutôt pertinent en fait !

**Comment by jillro** [comment]
Le problème, c'est que ça fait très *cursus honorum* dans un parti classique. D'abord tu milites puis tu gravis les échelons... ça ne fonctionne pas comme ça chez nous ! Créateur de groupe d'appui ne peut pas être un titre ou une récompense c'est juste un fait :)

**Comment by Sramyaguchi** [comment]
Comme Darckoune pour le premier point. C'est d'ailleurs comme sur BerniePB où les trophées sont clairement identifiés.

Pour le second point, c'est vraiment la première fois que quelqu'un commente là-dessus (et encore une fois BerniePB avait un système similaire et personne pourtant progressistes et bien de gauche ne s'en plaignait). Les gens ont toujours des critiques à formuler mais là on tente de mobiliser les jeunes pas forcément politisés qui s'impliquent doucement dans la campagne. Je suis pour garder le système actuel de gradation et le thème de la politique puisqu'il s'agit bien d'un outil de campagne.

Mais si des gens en interne veulent en parler on peut en discuter.

**Comment by jillro** [comment]
Ok aussi pour le premier point.

Pour le second point, j'ai déjà eu plusieurs remarques. Il y a aussi des gens politisés qui vont regarder ça. Choisissons une solution de consensus, d'autant que je ne nous pense pas incapable de trouver d'autres idées ;)
